version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile-app 
    ports:
      - 8000:8000 
    depends_on:
      - db   
  db:
    build:
      context: .
      dockerfile: dockerfile-mongodb
    ports:
      - 27017:27017   
    volumes:
      - ./data:/data/db